stages:
  - build-containers
  - build

include:
  - local: 'ci/docker-image-linux.yml'
 # - local: 'ci/docker-image-windows.yml' # Do not run this because it takes a lot of time. Run and upload manually

build:linux:
  image: $CI_REGISTRY_IMAGE/build-environment/linux
  stage: build
  script:
    - git submodule update --init
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./AppDir -DELPIDA_WEB_API_KEY=$ELPIDA_WEB_API_KEY
    - make -C build install
    - mkdir -p ./AppDir/usr/share/icons/default/apps/32/
    - mkdir -p ./AppDir/usr/share/metainfo/
    - mkdir -p ./AppDir/usr/share/applications/
    - cp -u ./images/Elpida-icon-minimal-circle-bg.svg ./AppDir/usr/share/icons/default/apps/32/elpida.svg
    - cp -u ./resources/dev.elpida.qt.metainfo.xml ./AppDir/usr/share/metainfo/dev.elpida.qt.metainfo.xml
    - cp -u ./resources/dev.elpida.qt.metainfo.xml ./AppDir/usr/share/metainfo/dev.elpida.qt.appdata.xml
    - cp -u ./resources/dev.elpida.qt.desktop ./AppDir/usr/share/applications/
    - appimage-builder --skip-tests
  artifacts:
    paths:
      - Elpida-latest-x86_64.AppImage
    expire_in: 2 days

build:windows:
  image: $CI_REGISTRY_IMAGE/build-environment/windows
  stage: build
  script:
    - git submodule update --init
    - x86_64-w64-mingw32.shared-cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install -DELPIDA_WEB_API_KEY=$ELPIDA_WEB_API_KEY
    - make -C build install
    - mkdir AppDir
    - /mxe/tools/copydlldeps.sh -c -f ./install/bin/elpida-qt.exe -S "/mxe/usr/x86_64-w64-mingw32.shared/bin/ /mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/" -R "./install ./build" -d ./AppDir
    - make -C build install -j$(nproc)
    - cp -r /mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/iconengines ./AppDir
    - cp -r /mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/imageformats ./AppDir
    - cp -r /mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/platforms ./AppDir
    - cp -r /mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/platformthemes ./AppDir
    - cp -r /mxe/usr/x86_64-w64-mingw32.shared/qt5/plugins/styles ./AppDir
    - cp /mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Svg.dll ./AppDir
    - mkdir ./AppDir/Benchmarks
    - find ./build/src/Benchmarks -type f -name '*.dll' -exec cp "{}" ./AppDir/Benchmarks \;
    - cp ./install/bin/elpida-qt.exe ./AppDir
    - cd ./AppDir
    - zip z -r .
    - cp ./z.zip ../Elpida-latest-x86_64.zip
    - cd ..
  artifacts:
    paths:
      - Elpida-latest-x86_64.zip
    expire_in: 2 days