image: ubuntu

build:
  stage: build
  script:
    - apt update
    - cp scripts/Linux/* .
    - chmod u+x ./*.sh
    - ./downloadPackages.sh
    - git submodule update --init
    - ./rebuildElpida.sh
    - ./createAppImage.sh
  artifacts:
    paths:
      - Elpida-latest-x86_64.AppImage
    expire_in: 2 days
