.build:linux:
  image: $CI_REGISTRY_IMAGE/build-environment/linux-$TARGET_ARCH
  stage: build
  tags:
    - $TARGET_ARCH
  environment:
    name: $DEPLOY_ENVIRONMENT
  script:
    - git submodule update --init
    - cmake -S .
      -B "$BUILD_DIR"
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"
      -DELPIDA_RELEASE=TRUE
      -DELPIDA_WEBSITE="$ELPIDA_WEBSITE"
      -DELPIDA_WEB_API_URL="$ELPIDA_WEB_API_URL"
      -DELPIDA_WEB_API_KEY="$ELPIDA_WEB_API_KEY"
      -DELPIDA_VERSION_MAJOR=$ELPIDA_VERSION_MAJOR
      -DELPIDA_VERSION_MINOR=$ELPIDA_VERSION_MINOR
      -DELPIDA_VERSION_REVISION=$ELPIDA_VERSION_REVISION
      -DELPIDA_VERSION_BUILD=$ELPIDA_VERSION_BUILD
    - make -C "$BUILD_DIR" -j$(nproc) install
  artifacts:
    expire_in: 2h30min
    paths:
      - $BUILD_DIR
      - $INSTALL_DIR

build:linux:amd64:
  variables:
    TARGET_ARCH: amd64
  dependencies:
    - docker-image:linux:amd64
  extends: .build:linux

build:linux:aarch64:
  variables:
    TARGET_ARCH: aarch64
  dependencies:
    - docker-image:linux:aarch64
  extends: .build:linux

#build:linux:armhf:
#  variables:
#    TARGET_ARCH: armhf
#  dependencies:
#    - docker-image:linux:armhf
#  extends: .build:linux