.build:linux:
  image: $IMAGE_NAME
  stage: build
  tags:
    - amd64
  environment:
    name: $DEPLOY_ENVIRONMENT
  script:
    - git submodule update --init
    - sed -i 's/cmake_minimum_required(VERSION 2.4.4)/cmake_minimum_required(VERSION 3.14.0)/' ./extern/zlib/CMakeLists.txt
    - cmake -S .
      -B "$BUILD_DIR"
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_TOOLCHAIN_FILE=./cmake-modules/$TARGET_ARCH-linux-cross.cmake
      -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"
      -DELPIDA_RELEASE=TRUE
      -DELPIDA_WEBSITE="$ELPIDA_WEBSITE"
      -DELPIDA_WEB_API_URL="$ELPIDA_WEB_API_URL"
      -DELPIDA_WEB_API_KEY="$ELPIDA_WEB_API_KEY"
      -DELPIDA_VERSION_MAJOR=$ELPIDA_VERSION_MAJOR
      -DELPIDA_VERSION_MINOR=$ELPIDA_VERSION_MINOR
      -DELPIDA_VERSION_REVISION=$ELPIDA_VERSION_REVISION
      -DELPIDA_VERSION_BUILD=$ELPIDA_VERSION_BUILD
    - make -C "$BUILD_DIR" -j$(nproc) install
    - rm -rf "$INSTALL_DIR/lib/*" "$INSTALL_DIR/bin/*png*" "$INSTALL_DIR/include/*" "$INSTALL_DIR/share/*"
  artifacts:
    expire_in: 2h30min
    paths:
      - $BUILD_DIR
      - $INSTALL_DIR

build:linux:amd64:
  variables:
    TARGET_ARCH: amd64
    TARGET_OS: linux
  dependencies:
    - docker-image:linux
  extends: .build:linux

build:linux:aarch64:
  variables:
    TARGET_ARCH: aarch64
    TARGET_OS: linux
  dependencies:
    - docker-image:linux
  extends: .build:linux