.package:linux:
  image: $IMAGE_NAME
  stage: package
  tags:
    - amd64
  script:
    - ./scripts/Linux/createAppImage.sh "$INSTALL_DIR" bin/elpida-qt $ELPIDA_VERSION_STRING $PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.AppImage
    - rm "$INSTALL_DIR/bin/elpida-qt"
    - ./scripts/Linux/createAppImage.sh "$INSTALL_DIR" bin/elpida-cli $ELPIDA_VERSION_STRING $PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.AppImage
    - sha256sum "$PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.AppImage" > $PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.SHA256SUMS
    - sha256sum "$PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.AppImage" > $PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.SHA256SUMS
  artifacts:
    expire_in: 2h30min
    paths:
      - $PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.AppImage
      - $PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.SHA256SUMS
      - $PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.AppImage
      - $PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.SHA256SUMS

package:linux:amd64:
  variables:
    TARGET_ARCH: amd64
    TARGET_OS: linux
    TARGET_ARCH_APPIMAGE_RUNTIME: x86_64
    TARGET_ARCH_APPIMAGE_APT: amd64
  dependencies:
    - build:linux:amd64
  extends: .package:linux

package:linux:aarch64:
  variables:
    TARGET_ARCH: aarch64
    TARGET_OS: linux
    TARGET_ARCH_APPIMAGE_RUNTIME: aarch64
    TARGET_ARCH_APPIMAGE_APT: arm64
  dependencies:
    - build:linux:aarch64
  extends: .package:linux