.package:windows:
  image: $CI_REGISTRY_IMAGE/build-environment/windows-$TARGET_ARCH
  stage: package
  tags:
    - $TARGET_ARCH
  script:
    - currentDir=$(pwd)
    - stagingDir=$(mktemp -d -t ci-XXXXXXXXXX)
    - /mxe/tools/copydlldeps.sh -c
      -f "$INSTALL_DIR/bin/elpida-qt.exe"
      -S "/mxe/usr/x86_64-w64-mingw32.static/bin/ /mxe/usr/x86_64-w64-mingw32.static/qt5/bin/"
      -R "$INSTALL_DIR  $BUILD_DIR"
      -d "$stagingDir"
    - cp -r /mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/iconengines "$stagingDir"
    - cp -r /mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats "$stagingDir"
    - cp -r /mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/platforms "$stagingDir"
    - cp -r /mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/platformthemes "$stagingDir"
    - cp -r /mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/styles "$stagingDir"
    - mkdir "$stagingDir/Benchmarks"
    - find "$BUILD_DIR/src/Benchmarks" -type f -name '*.exe' -exec cp "{}" "$stagingDir/Benchmarks" \;
    - cp "$INSTALL_DIR/bin/elpida-qt.exe" "$stagingDir"
    - cp "$INSTALL_DIR/bin/elpida-info-dumper.exe" "$stagingDir"
    - cp "$INSTALL_DIR/bin/qt.conf" "$stagingDir"
    - cp -r "$INSTALL_DIR/bin/assets" "$stagingDir"
    - cd "$stagingDir"
    - zip z -r .
    - cp ./z.zip "$currentDir/$PACKAGE_FILENAME.zip"
    - cd "$currentDir"
    - sha256sum "$PACKAGE_FILENAME.zip" > SHA256SUMS
    - rm -rf "$stagingDir"
  artifacts:
    paths:
      - $PACKAGE_FILENAME.zip
      - SHA256SUMS

package:windows:amd64:
  variables:
    TARGET_ARCH: amd64
  dependencies:
    - build:windows:amd64
  extends: .package:windows