function(generate_environment_file file command)
    set(ENV_FILE ${file})
    file(WRITE ${ENV_FILE} "#!/bin/bash\n")

    if (ANDROID)
        set(TRIPLE ${CMAKE_LIBRARY_ARCHITECTURE}${ANDROID_NATIVE_API_LEVEL})
        file(APPEND ${ENV_FILE} "export CC=\"${CMAKE_C_COMPILER} --target=${TRIPLE}\"\n")
        file(APPEND ${ENV_FILE} "export CXX=\"${CMAKE_CXX_COMPILER} --target=${TRIPLE}\"\n")
        file(APPEND ${ENV_FILE} "export STRIP=\"${ANDROID_STRIP}\"\n")
    else ()
        file(APPEND ${ENV_FILE} "export CC=\"${CMAKE_C_COMPILER}\"\n")
        file(APPEND ${ENV_FILE} "export CXX=\"${CMAKE_CXX_COMPILER}\"\n")
        file(APPEND ${ENV_FILE} "export STRIP=\"${CMAKE_STRIP}\"\n")
    endif ()

    if (NOT TRIPLE)
        if (CMAKE_C_COMPILER_ID STREQUAL "GNU")
            execute_process(COMMAND ${CMAKE_C_COMPILER} -dumpmachine OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE TRIPLE)
        elseif (CMAKE_C_COMPILER_ID STREQUAL "Clang")
            set(TRIPLE ${TARGET_TRIPLE})
        endif ()
    endif ()

    file(APPEND ${ENV_FILE} "export AR=\"${CMAKE_AR}\"\n")
    file(APPEND ${ENV_FILE} "export RANLIB=\"${CMAKE_RANLIB}\"\n")
    file(APPEND ${ENV_FILE} "export CFLAGS=\"${CMAKE_C_FLAGS}\"\n")
    file(APPEND ${ENV_FILE} "export CXXFLAGS=\"${CMAKE_CXX_FLAGS}\"\n")
    file(APPEND ${ENV_FILE} "export TRIPLE=\"${TRIPLE}\"\n")
    file(APPEND ${ENV_FILE} "export SYSROOT=\"${CMAKE_SYSROOT}\"\n")
    file(APPEND ${ENV_FILE} ${command})
    file(CHMOD ${ENV_FILE} PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_WRITE GROUP_EXECUTE WORLD_READ WORLD_WRITE WORLD_EXECUTE)
endfunction()
