if (NOT ELPIDA_VERSION_MAJOR)
   set(ELPIDA_VERSION_MAJOR 0)
endif()

if (NOT ELPIDA_VERSION_MINOR)
   set(ELPIDA_VERSION_MINOR 0)
endif()

if (NOT ELPIDA_VERSION_REVISION)
   set(ELPIDA_VERSION_REVISION 1)
endif()

if (NOT ELPIDA_VERSION_BUILD)
   set(ELPIDA_VERSION_BUILD 1000)
endif()

if (ELPIDA_BETA EQUAL 1)
    add_definitions(-DELPIDA_BETA=1)
endif()