option(TARGET_PREFIX "The cross target prefix" "")

if (TARGET_PREFIX)
    # replace last -
    string(REGEX REPLACE "-$" "" TARGET_TRIPLE ${TARGET_PREFIX})

    string(REGEX REPLACE "-" ";" TARGET_PARTS ${TARGET_PREFIX})
    list(GET TARGET_PARTS 0 CMAKE_SYSTEM_PROCESSOR)
    list(GET TARGET_PARTS 1 TARGET_OS)
    list(GET TARGET_PARTS 2 TARGET_ENV)

    if (TARGET_OS STREQUAL "w64")
        set(CMAKE_SYSTEM_NAME Windows)
    elseif (TARGET_OS STREQUAL "linux")
        set(CMAKE_SYSTEM_NAME Linux)
    else ()
        set(CMAKE_SYSTEM_NAME ${TARGET_OS})
    endif ()
endif ()

set(CMAKE_C_COMPILER ${TARGET_PREFIX}clang)
set(CMAKE_CXX_COMPILER ${TARGET_PREFIX}clang++)
set(CMAKE_ASM_COMPILER ${TARGET_PREFIX}clang)
set(CMAKE_LINKER_TYPE LLD)

if (CMAKE_SYSROOT)
    set(CMAKE_C_FLAGS "--sysroot=${CMAKE_SYSROOT}")
    set(CMAKE_CXX_FLAGS "--sysroot=${CMAKE_SYSROOT}")
    set(CMAKE_LD_FLAGS "--sysroot=${CMAKE_SYSROOT}")
    set(CMAKE_ASM_FLAGS "--sysroot=${CMAKE_SYSROOT}")

    set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif ()