# Force release for here, we do not want 2gb binaries
set(CMAKE_BUILD_TYPE Release)
set(ENABLE_STATIC ON CACHE INTERNAL "")
set(LLVM_ENABLE_PROJECTS clang CACHE INTERNAL "")
set(CMAKE_SKIP_INSTALL_RPATH ON CACHE INTERNAL "")
set(BUILD_SHARED_LIBS OFF CACHE INTERNAL "")
set(LLVM_STATIC_LINK_CXX_STDLIB ON CACHE INTERNAL "")
set(LIBCLANG_BUILD_STATIC ON CACHE INTERNAL "")
set(LLVM_TARGETS_TO_BUILD X86 CACHE INTERNAL "")
set(LLVM_ENABLE_ZSTD OFF CACHE INTERNAL "")
set(LLVM_BUILD_DOCS OFF CACHE INTERNAL "")
set(LLVM_BUILD_EXAMPLES OFF CACHE INTERNAL "")
set(LLVM_BUILD_RUNTIME OFF CACHE INTERNAL "")
set(LLVM_BUILD_RUNTIMES OFF CACHE INTERNAL "")
set(LLVM_BUILD_TESTS OFF CACHE INTERNAL "")
set(LLVM_BUILD_TOOLS OFF CACHE INTERNAL "")
set(LLVM_BUILD_UTILS OFF CACHE INTERNAL "")
set(LLVM_ENABLE_BINDINGS OFF CACHE INTERNAL "")
set(LLVM_ENABLE_DOXYGEN OFF CACHE INTERNAL "")
set(LLVM_ENABLE_OCAMLDOC OFF CACHE INTERNAL "")
set(LLVM_ENABLE_SPHINX OFF CACHE INTERNAL "")
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE INTERNAL "")
set(LLVM_INCLUDE_EXAMPLES OFF CACHE INTERNAL "")
set(LLVM_INCLUDE_TESTS OFF CACHE INTERNAL "")
set(LLVM_INCLUDE_DOCS OFF CACHE INTERNAL "")
set(LLVM_INCLUDE_GO_TESTS OFF CACHE INTERNAL "")
set(LLVM_INCLUDE_RUNTIMES OFF CACHE INTERNAL "")
set(LLVM_INCLUDE_TOOLS ON CACHE INTERNAL "")
set(LLVM_INCLUDE_UTILS OFF CACHE INTERNAL "")
set(LLVM_BUILD_BENCHMARKS OFF CACHE INTERNAL "")
set(LLVM_BUILD_INSTRUMENTED_COVERAGE OFF CACHE INTERNAL "")
set(LLVM_BUILD_LLVM_DYLIB OFF CACHE INTERNAL "")
set(LLVM_ENABLE_DIA_SDK OFF CACHE INTERNAL "")
set(LLVM_ENABLE_DOXYGEN OFF CACHE INTERNAL "")
set(LLVM_ENABLE_DOXYGEN_QT_HELP OFF CACHE INTERNAL "")
set(LLVM_ENABLE_HTTPLIB OFF CACHE INTERNAL "")
set(LLVM_ENABLE_IDE OFF CACHE INTERNAL "")
set(LLVM_ENABLE_LIBPFM OFF CACHE INTERNAL "")
set(LLVM_ENABLE_SPHINX OFF CACHE INTERNAL "")
set(LLVM_INDIVIDUAL_TEST_COVERAGE OFF CACHE INTERNAL "")
set(LLVM_LINK_LLVM_DYLIB OFF CACHE INTERNAL "")

if (ELPIDA_WINDOWS)
    # Apply our custom patch to allow to build for windows xp
    execute_process(COMMAND patch --directory=${CMAKE_CURRENT_SOURCE_DIR}/llvm -p1 --input=${CMAKE_CURRENT_FUNCTION_LIST_DIR}/llvm.WindowsXp.patch)
endif ()

add_subdirectory(llvm/llvm)

set(LLVM_INCLUDE_DIRECTORIES
        ${LLVM_SOURCE_DIR}/include
        ${LLVM_SOURCE_DIR}/../clang/include
        ${CMAKE_CURRENT_BINARY_DIR}/llvm/llvm/include
        ${CMAKE_CURRENT_BINARY_DIR}/llvm/llvm/tools/clang/include
        PARENT_SCOPE
)