.build:
  image: $IMAGE_NAME
  stage: build
  tags:
    - amd64
  environment:
    name: $DEPLOY_ENVIRONMENT
  script:
    - git submodule update --init --depth=1
    - cmake -S .
      -B "$BUILD_DIR"
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_SYSROOT=$TARGET_SYSROOT
      -DTARGET_PREFIX=$TARGET_PREFIX
      -DCMAKE_TOOLCHAIN_FILE=./cmake-modules/llvm-cross.cmake
      -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"
      -DELPIDA_WEBSITE="$ELPIDA_WEBSITE"
      -DELPIDA_WEB_API_URL="$ELPIDA_WEB_API_URL"
      -DELPIDA_WEB_API_KEY="$ELPIDA_WEB_API_KEY"
      -DELPIDA_VERSION_MAJOR=$ELPIDA_VERSION_MAJOR
      -DELPIDA_VERSION_MINOR=$ELPIDA_VERSION_MINOR
      -DELPIDA_VERSION_REVISION=$ELPIDA_VERSION_REVISION
      -DELPIDA_VERSION_BUILD=$ELPIDA_VERSION_BUILD
    # LLVM build randomly fails with these targets so pre-build them
    - make -C "$BUILD_DIR" -j$(nproc) llvm-tblgen llvm-config clang-tblgen
    - make -C "$BUILD_DIR" -j$(nproc) install
  artifacts:
    expire_in: 2h30min
    paths:
      - $INSTALL_DIR

build:linux:x86_64:
  variables:
    TARGET_SYSROOT: /
    TARGET_TRIPLE: x86_64-linux-gnu
  dependencies:
    - docker-image
  extends: .build

build:linux:arm:
  variables:
    TARGET_SYSROOT: /
    TARGET_TRIPLE: arm-linux-gnueabihf
  dependencies:
    - docker-image
  extends: .build

build:linux:aarch64:
  variables:
    TARGET_SYSROOT: /
    TARGET_TRIPLE: aarch64-linux-gnu
  dependencies:
    - docker-image
  extends: .build

build:windows:x86_64:
  variables:
    TARGET_SYSROOT: /opt/toolchains/llvm-mingw/x86_64-w64-mingw32
    TARGET_PREFIX: x86_64-w64-mingw32-
  dependencies:
    - docker-image
  extends: .build

build:windows:i686:
  variables:
    TARGET_SYSROOT: /opt/toolchains/llvm-mingw/i686-w64-mingw32
    TARGET_PREFIX: i686-w64-mingw32-
  dependencies:
    - docker-image
  extends: .build

build:windows:aarch64:
  variables:
    TARGET_SYSROOT: /opt/toolchains/llvm-mingw/aarch64-w64-mingw32
    TARGET_PREFIX: aarch64-w64-mingw32-
  dependencies:
    - docker-image
  extends: .build