.Package Linux:
  image: $IMAGE_NAME
  stage: package
  tags:
    - amd64
  script:
    - cp -r "$INSTALL_DIR" "qt"
    - mv "$INSTALL_DIR" "cli"
    - rm "qt/bin/elpida-cli"
    - rm "cli/bin/elpida-qt"
    - ./scripts/Linux/setupDependencies.sh "$PWD/cli/bin/elpida-cli" "$PWD/cli" "/opt/sysroots/$TARGET_TRIPLE" "\$this_dir"
    - ./scripts/Linux/finalizeAppDir.sh "$PWD/cli" bin/elpida-cli $PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.tar.xz
    - ./scripts/Linux/setupDependencies.sh "$PWD/qt/bin/elpida-qt" "$PWD/qt" "/opt/sysroots/$TARGET_TRIPLE" "\$this_dir"
    - ./scripts/Linux/finalizeAppDir.sh "$PWD/qt" bin/elpida-qt $PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.tar.xz
    - sha256sum "$PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.tar.xz" > $PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.SHA256SUMS
    - sha256sum "$PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.tar.xz" > $PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.SHA256SUMS
  artifacts:
    expire_in: 2h30min
    paths:
      - $PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.tar.xz
      - $PACKAGE_FILENAME.$PACKAGE_QT_SUFFIX.SHA256SUMS
      - $PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.tar.xz
      - $PACKAGE_FILENAME.$PACKAGE_CLI_SUFFIX.SHA256SUMS

.Package Windows:
  image: $IMAGE_NAME
  stage: package
  tags:
    - amd64
  script:
    - |
      currentDir=$(pwd)
      cd "$INSTALL_DIR/bin"
      zip z -r .
      cp ./z.zip "$currentDir/$PACKAGE_FILENAME.zip"
      cd "$currentDir"
      sha256sum "$PACKAGE_FILENAME.zip" > SHA256SUMS
  artifacts:
    paths:
      - $PACKAGE_FILENAME.zip
      - SHA256SUMS

Package (x86_64-linux-gnu):
  variables:
    TARGET_TRIPLE: x86_64-linux-gnu
  dependencies:
    - Build (x86_64-linux-gnu)
  extends: .Package Linux

Package (i386-linux-gnu):
  variables:
    TARGET_TRIPLE: i386-linux-gnu
  dependencies:
    - Build (i386-linux-gnu)
  extends: .Package Linux

Package (arm-linux-gnueabihf):
  variables:
    TARGET_TRIPLE: arm-linux-gnueabihf
  dependencies:
    - Build (arm-linux-gnueabihf)
  extends: .Package Linux

Package (aarch64-linux-gnu):
  variables:
    TARGET_TRIPLE: aarch64-linux-gnu
  dependencies:
    - Build (aarch64-linux-gnu)
  extends: .Package Linux

Package (riscv64-linux-gnu):
  variables:
    TARGET_TRIPLE: riscv64-linux-gnu
  dependencies:
    - Build (riscv64-linux-gnu)
  extends: .Package Linux

Package (x86_64-w64-mingw32):
  variables:
    TARGET_TRIPLE: x86_64-w64-mingw32
  dependencies:
    - Build (x86_64-w64-mingw32)
  extends: .Package Windows

Package (i686-w64-mingw32):
  variables:
    TARGET_TRIPLE: i686-w64-mingw32
  dependencies:
    - Build (i686-w64-mingw32)
  extends: .Package Windows

Package (aarch64-w64-mingw32):
  variables:
    TARGET_TRIPLE: aarch64-w64-mingw32
  dependencies:
    - Build (aarch64-w64-mingw32)
  extends: .Package Windows